### ISSUE TITLE
What speeds and feeds?

### ISSUE THREAD

**Issue by HjortCreations** [rolohaun/Defiant#4]
I am on the way to design a cross-gantry printer, but with the Ultimaker rod style design, when I stumbled across this :-D
Instead of me starting all over, I maybe should build this?
What are you looking at for speeds and feeds when printing with this?

Personnally I like the RatRig Z-axis assembly and the 30x30 extrusions...

**Comment by rolohaun** [comment]
been a while since I used mine but it was printing 16 minute benchies pretty easily. was 10 - 15k accel and 200mm/s

**Comment by HjortCreations** [comment]
Thanks
I'll look into it a bit more, and I might build one soon...
BTW love your work ;-)

**Comment by rolohaun** [comment]
awesome, feel free to join my discord there is another user who built one. I am going to be doing more videos on it soon

**Comment by HjortCreations** [comment]
I'm not that active on Discord, but would like to discuss some design ideas, so might take that up ;-)
